### ISSUE TITLE
Generated Output: ImGui::End() needs to be outside of if block.

### ISSUE THREAD

**Issue by sigmareaver** [Raais/ImStudio#13]
`ImGui::End()` should always be called, even if `ImGui::Begin()` returns false. Otherwise ImGui will assert on a begin/end stack mismatch.

This might seem confusing initially, because ImGui widgets that have Begin/End calls should have their End calls inside the if block. However, that rule does not apply to ImGui windows.

**Comment by Raais** [comment]
Thanks for catching that. Didnt know 👍
